import { describe, expect, it, vi } from "vitest";

// The validator imports the real rpg data tree, which in turn pulls in
// `utils/Webhooks` (via SpecialItems → vote rewards). Webhooks construct
// at module-load time and need URL envs we don't want to require in tests.
vi.mock("../utils/Webhooks", () => ({
    voteWebhook: { send: vi.fn() },
    commandLogsWebhook: { send: vi.fn() },
    specialLogsWebhook: { send: vi.fn() },
    transactionLogsWebhook: { send: vi.fn() },
    raidWebhook: { send: vi.fn() },
    tradeWebhook: { send: vi.fn() },
    dungeonLogsWebhook: { send: vi.fn() },
    refundWebhook: { send: vi.fn() },
    sentryLogsWebhook: { send: vi.fn() },
    accountLogsWebhook: { send: vi.fn() },
    fightWebhook: { send: vi.fn() },
    fightLogsWebhook: { send: vi.fn() },
    fightStatsWebhook: { send: vi.fn() },
}));

import { validateRegistries } from "./validate";

describe("validateRegistries", () => {
    it("reports no static-data issues against the current tree", () => {
        // Stand discs (id pattern "*.$disc$") are generated by
        // `EventNPCGenerator` at boot, after this validator runs in the test
        // harness. Filter those false-positives so this test catches real
        // duplicates / typos in static data without requiring the dynamic
        // generation pass.
        const errors = validateRegistries().filter(
            (e) => !e.includes(".$disc$"),
        );
        expect(errors).toEqual([]);
    });
});
